# Generated by Django 5.1.7 on 2025-08-01 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('philosophy', 'Philosophy'), ('theology', 'Theology')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('image', models.ImageField(help_text='Department image', upload_to='departments/')),
                ('description', models.TextField(help_text='Department description')),
                ('link_url', models.CharField(help_text='Link to department page', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Department',
                'verbose_name_plural': 'Academic Departments',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('book', 'Book (Academic Affairs)'), ('heart', 'Heart (Spiritual Formation)'), ('users', 'Users (Student Affairs)'), ('home', 'Home (Pastoral Ministries)'), ('library', 'Library (Library & Research)'), ('calculator', 'Calculator (Administration)')], max_length=20)),
                ('link_url', models.CharField(help_text='Link to committee/office page', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Committee/Office',
                'verbose_name_plural': 'Committees/Offices',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Excellence in Theological & Philosophical Education', max_length=200)),
                ('subtitle', models.TextField(default='Discover what makes Holy Spirit Major Seminary a center for spiritual and intellectual formation')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Featured Section',
                'verbose_name_plural': 'Featured Sections',
            },
        ),
        migrations.CreateModel(
            name='FormationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Formation Step',
                'verbose_name_plural': 'Formation Steps',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='RectorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Rev. Fr. Paul Gomes', max_length=100)),
                ('position', models.CharField(default='Rector, Holy Spirit Major Seminary', max_length=100)),
                ('image', models.ImageField(help_text="Upload rector's portrait image", upload_to='rector/')),
                ('quote', models.TextField(help_text='Inspirational quote from the rector')),
                ('message_paragraph_1', models.TextField(help_text="First paragraph of the rector's message")),
                ('message_paragraph_2', models.TextField(help_text="Second paragraph of the rector's message")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rector Message',
                'verbose_name_plural': 'Rector Messages',
            },
        ),
        migrations.CreateModel(
            name='DepartmentFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='about.academicdepartment')),
            ],
            options={
                'verbose_name': 'Department Feature',
                'verbose_name_plural': 'Department Features',
                'ordering': ['order'],
            },
        ),
    ]
