# Generated by Django 5.1.7 on 2025-08-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_academicdepartment_committeeoffice_featuredsection_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RectorWelcome',
        ),
        migrations.AlterField(
            model_name='rectormessage',
            name='quote',
            field=models.TextField(blank=True, help_text='Inspirational quote from the rector', null=True),
        ),
    ]
