# Generated by Django 5.1.7 on 2025-08-08 08:02

import django.db.models.deletion
import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_delete_rectorwelcome_alter_rectormessage_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rectormessage',
            name='message_paragraph_1',
        ),
        migrations.RemoveField(
            model_name='rectormessage',
            name='message_paragraph_2',
        ),
        migrations.CreateModel(
            name='RectorMessageParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_summernote.fields.SummernoteTextField(help_text='Rich text content for this paragraph with formatting options')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this paragraph (0 = first, 1 = second, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rector_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='about.rectormessage')),
            ],
            options={
                'verbose_name': 'Rector Message Paragraph',
                'verbose_name_plural': 'Rector Message Paragraphs',
                'ordering': ['order'],
            },
        ),
    ]
