# Generated by Django 5.1.7 on 2025-03-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnkurPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='ankur/')),
                ('date_published', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DipttoSakhyoPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issue', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='diptto_sakhyo/')),
                ('date_published', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
