# Generated by Django 5.1.7 on 2025-08-04 15:00

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ankurpublication',
            options={'ordering': ['-date_published'], 'verbose_name': 'Ankur Publication', 'verbose_name_plural': 'Ankur Publications'},
        ),
        migrations.AlterModelOptions(
            name='dipttosakhyopublication',
            options={'ordering': ['-date_published'], 'verbose_name': 'Diptto Sakhyo Publication', 'verbose_name_plural': 'Diptto Sakhyo Publications'},
        ),
        migrations.RemoveField(
            model_name='ankurpublication',
            name='author',
        ),
        migrations.RemoveField(
            model_name='ankurpublication',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ankurpublication',
            name='file',
        ),
        migrations.RemoveField(
            model_name='dipttosakhyopublication',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dipttosakhyopublication',
            name='file',
        ),
        migrations.AddField(
            model_name='ankurpublication',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ankurpublication',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ankurpublication',
            name='file_size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ankurpublication',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ankurpublication',
            name='pdf_file',
            field=models.FileField(default=django.utils.timezone.now, help_text='Upload PDF file only', upload_to='publications/ankur/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ankurpublication',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional thumbnail image for the publication', null=True, upload_to='publications/ankur/thumbnails/'),
        ),
        migrations.AddField(
            model_name='dipttosakhyopublication',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dipttosakhyopublication',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dipttosakhyopublication',
            name='file_size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dipttosakhyopublication',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dipttosakhyopublication',
            name='pdf_file',
            field=models.FileField(default=django.utils.timezone.now, help_text='Upload PDF file only', upload_to='publications/diptto_sakhyo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dipttosakhyopublication',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional thumbnail image for the publication', null=True, upload_to='publications/diptto_sakhyo/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='ankurpublication',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dipttosakhyopublication',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
