# Generated by Django 5.1.7 on 2025-08-05 14:53

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['category', 'title']},
        ),
        migrations.AlterModelOptions(
            name='enrollmentrequirement',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AlterModelOptions(
            name='examinformation',
            options={'ordering': ['-exam_date']},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['category', 'order', 'question']},
        ),
        migrations.AlterModelOptions(
            name='spiritualguidance',
            options={'ordering': ['-is_featured', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tuitionfee',
            options={'ordering': ['fee_type', 'title']},
        ),
        migrations.RenameField(
            model_name='examinformation',
            old_name='date',
            new_name='exam_date',
        ),
        migrations.AddField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollmentrequirement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollmentrequirement',
            name='is_mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enrollmentrequirement',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examinformation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examinformation',
            name='exam_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examinformation',
            name='exam_type',
            field=models.CharField(choices=[('midterm', 'Midterm'), ('final', 'Final'), ('entrance', 'Entrance'), ('comprehensive', 'Comprehensive')], default='final', max_length=50),
        ),
        migrations.AddField(
            model_name='examinformation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examinformation',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('admission', 'Admission'), ('academic', 'Academic'), ('financial', 'Financial'), ('student_life', 'Student Life'), ('spiritual', 'Spiritual'), ('general', 'General')], default='general', max_length=100),
        ),
        migrations.AddField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spiritualguidance',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='spiritualguidance',
            name='category',
            field=models.CharField(choices=[('prayer', 'Prayer'), ('meditation', 'Meditation'), ('scripture', 'Scripture'), ('reflection', 'Reflection'), ('guidance', 'Guidance'), ('inspiration', 'Inspiration')], default='guidance', max_length=100),
        ),
        migrations.AddField(
            model_name='spiritualguidance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spiritualguidance',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('transferred', 'Transferred'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tuitionfee',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tuitionfee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tuitionfee',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tuitionfee',
            name='fee_type',
            field=models.CharField(choices=[('tuition', 'Tuition'), ('registration', 'Registration'), ('library', 'Library'), ('laboratory', 'Laboratory'), ('accommodation', 'Accommodation'), ('other', 'Other')], default='tuition', max_length=50),
        ),
        migrations.AddField(
            model_name='tuitionfee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('forms', 'Forms'), ('requirements', 'Requirements'), ('guidelines', 'Guidelines'), ('handbooks', 'Handbooks'), ('applications', 'Applications'), ('other', 'Other')], default='forms', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='student_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=300),
        ),
    ]
