# Generated by Django 5.1.7 on 2025-07-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main title for the hero slide', max_length=200)),
                ('subtitle', models.TextField(help_text='Subtitle description', max_length=500)),
                ('image', models.ImageField(help_text='Upload hero slide image (recommended: 1920x800px)', upload_to='hero_slides/')),
                ('cta_text', models.CharField(default='Learn More', help_text='Call-to-action button text', max_length=50)),
                ('cta_link', models.CharField(help_text='URL for the call-to-action button (e.g., /admissions/apply)', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this slide should be displayed')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
