# Generated by Django 5.1.7 on 2025-08-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslide',
            name='cta_link',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='cta_text',
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle',
            field=models.TextField(blank=True, help_text='Optional subtitle description', max_length=500, null=True),
        ),
    ]
