# Generated by Django 5.2.5 on 2025-08-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminary', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
