# Generated by Django 4.2 on 2025-08-21 12:00

from django.db import migrations, models

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Department = apps.get_model("seminary", "Department")
    Faculty = apps.get_model("seminary", "Faculty")
    db_alias = schema_editor.connection.alias
    
    # Create the departments
    departments = {
        "philosophy": Department.objects.using(db_alias).create(name="Department of Philosophy", slug="philosophy"),
        "theology": Department.objects.using(db_alias).create(name="Department of Theology", slug="theology"),
        "administration": Department.objects.using(db_alias).create(name="Administration", slug="administration"),
    }

    # Update the faculty members
    for faculty in Faculty.objects.using(db_alias).all():
        if faculty.department in departments:
            faculty.departments.add(departments[faculty.department])

def reverse_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Department = apps.get_model("seminary", "Department")
    Faculty = apps.get_model("seminary", "Faculty")
    db_alias = schema_editor.connection.alias

    # Update the faculty members
    for faculty in Faculty.objects.using(db_alias).all():
        if faculty.departments.count() > 0:
            faculty.department = faculty.departments.first().slug
            faculty.save()

    # Delete the departments
    Department.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('seminary', '0002_delete_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='departments',
            field=models.ManyToManyField(related_name='faculty', to='seminary.department'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.RemoveField(
            model_name='faculty',
            name='department',
        ),
    ]
