# Generated by Django 5.2.5 on 2025-08-22 10:49

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminary', '0003_auto_20250821_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='responsibilities',
            field=tinymce.models.HTMLField(blank=True, help_text='Committee responsibilities and duties'),
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='Department description with rich formatting'),
        ),
        migrations.AddField(
            model_name='page',
            name='excerpt',
            field=tinymce.models.HTMLField(blank=True, help_text='Short excerpt or summary'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=tinymce.models.HTMLField(help_text='Announcement content with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='description',
            field=tinymce.models.HTMLField(help_text='Committee description with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(help_text='Event description with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='bio',
            field=tinymce.models.HTMLField(help_text='Faculty biography with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='qualifications',
            field=tinymce.models.HTMLField(blank=True, help_text='Academic qualifications with formatting'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=tinymce.models.HTMLField(help_text='News content with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(help_text='Page content with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='abstract',
            field=tinymce.models.HTMLField(blank=True, help_text='Publication abstract with formatting'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=tinymce.models.HTMLField(help_text='Publication content with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=tinymce.models.HTMLField(help_text='Use rich text formatting for address'),
        ),
    ]
