# Generated by Django 5.2.5 on 2025-08-23 07:12

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminary', '0004_committee_responsibilities_department_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('rector', 'Rector Welcome'), ('director', 'Director Message')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('leader_name', models.CharField(max_length=100)),
                ('leader_title', models.CharField(max_length=100)),
                ('leader_photo', models.ImageField(blank=True, help_text="Leader's photo", null=True, upload_to='leadership/')),
                ('message_content', tinymce.models.HTMLField(help_text='Main message content with rich text formatting')),
                ('quote', models.TextField(blank=True, help_text='Inspirational quote or highlight')),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('background_image', models.ImageField(blank=True, help_text='Background image for the page', null=True, upload_to='leadership/backgrounds/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leadership Message',
                'verbose_name_plural': 'Leadership Messages',
                'ordering': ['message_type'],
            },
        ),
    ]
