# Generated by Django 5.2.5 on 2025-08-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminary', '0005_leadershipmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadershipmessage',
            name='message_type',
            field=models.CharField(choices=[('rector', 'Rector Welcome'), ('director', 'Director Message'), ('spiritual_director', 'Spiritual Director Message')], max_length=20, unique=True),
        ),
    ]
