# Generated by Django 5.2.5 on 2025-08-30 14:49

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminary', '0006_alter_leadershipmessage_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='committee',
            name='chairperson',
        ),
        migrations.AddField(
            model_name='committee',
            name='advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_committees', to='seminary.faculty'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='bio',
            field=tinymce.models.HTMLField(blank=True, help_text='Faculty biography with rich text formatting', null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(choices=[('ankur', 'Ankur - Newsletter'), ('diptto_sakhyo', 'Diptto Sakhyo - Major Seminary Journal'), ('prodipon', 'Prodipon - Theological Journal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='committee',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='committees', to='seminary.committeemember'),
        ),
    ]
