# Generated by Django 5.2.5 on 2025-08-31 02:32

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminary', '0007_committeemember_remove_committee_chairperson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminaryAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the administrator', max_length=200)),
                ('photo', models.ImageField(blank=True, help_text="Administrator's photo (recommended: 400x400px)", null=True, upload_to='administration/')),
                ('designation', models.CharField(help_text='Official title/position (e.g., Rector, Vice Rector, Bursar)', max_length=200)),
                ('bio', tinymce.models.HTMLField(blank=True, help_text='Brief biography or background information', null=True)),
                ('email', models.EmailField(blank=True, help_text='Official email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('office_location', models.CharField(blank=True, help_text='Office location or room number', max_length=100)),
                ('office_hours', models.CharField(blank=True, help_text='Available office hours', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
                ('start_date', models.DateField(blank=True, help_text='When this person started in this role', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seminary Administrator',
                'verbose_name_plural': 'Seminary Administration',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='excerpt',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
