# Generated by Django 4.2 on 2025-09-06 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seminary', '0009_sitesettings_hsit_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Congregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diocese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('student_type', models.CharField(choices=[('current', 'Current Student'), ('past', 'Past Student')], default='current', max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('course', models.CharField(choices=[('diploma', 'Diploma'), ('full_course', 'Full Course'), ('philosophy', 'Philosophy'), ('theology', 'Theology')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('is_active', models.BooleanField(default=True)),
                ('congregation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seminary.congregation')),
                ('diocese', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seminary.diocese')),
            ],
            options={
                'ordering': ['-year', 'name'],
            },
        ),
    ]
