# Generated by Django 4.2 on 2025-09-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminary', '0010_congregation_diocese_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='congregation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='diocese',
        ),
        migrations.AddField(
            model_name='student',
            name='affiliation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='affiliation_type',
            field=models.CharField(blank=True, choices=[('diocese', 'Diocese'), ('congregation', 'Congregation')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Congregation',
        ),
        migrations.DeleteModel(
            name='Diocese',
        ),
    ]
