# Generated by Django 4.2 on 2025-09-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminary', '0011_remove_student_congregation_remove_student_diocese_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='affiliation_type',
        ),
        migrations.AddField(
            model_name='student',
            name='belongs_to',
            field=models.CharField(blank=True, choices=[('diocese', 'Diocese'), ('congregation', 'Congregation')], max_length=20, null=True, verbose_name='Belongs to'),
        ),
        migrations.AddField(
            model_name='student',
            name='diocese_congregation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Diocese/Congregation'),
        ),
    ]
